### PR TITLE
Late 2023 Production update -> redesign

### PR DESCRIPTION
**Pull request by TyHil**
Ditto of PR #132 just to update redesign with recent changes.

I believe this should be a normal merge, not a squash and merge

### CODE REVIEW

**Comment by TyHil** [comment]
Yeah I'm not sure how tho, since we can't make a merge commit on develop. What do you think?

**Comment by Jake3231** [comment]
Since we're targeting redesign, shouldn't we be able to do normal conflict resolution locally?

**Comment by TyHil** [comment]
Oh yeah I guess so, no PR necessary. I can do that.

**Comment by TyHil** [comment]
Done

**Pull request merged**
