### PR TITLE
251 feature request compare colors on lhs

### PR DESCRIPTION
**Pull request by TatvikReddy**
# Overview

This pull request enhances the user experience by ensuring that the compare colors are consistently displayed on the left-hand side (LHS) checkboxes in the search results, matching the colors used in the right-hand side (RHS) compare table. This visual alignment makes it easier for users to correlate items between the search results and the compare view.

# What Changed

- **SearchResultsTable.tsx:**
  - Imported `searchQueryColors` to access the array of colors used for comparison items.
  - Calculated `colorMap` to map each search result to a specific color based on its index.
  - Passed the corresponding color to each `Row` component as a new `color` prop.

- **`Row` Component in `SearchResultsTable.tsx`:**
  - Updated the `RowProps` type to include the new `color` prop.
  - Applied the passed `color` to the compare checkbox using the `sx` prop, ensuring the checkbox on the LHS matches the color in the compare table.

- **Consistency with Compare Table:**
  - Ensured that both the search results checkboxes and the compare table checkboxes use the same color logic, derived from `searchQueryColors`.

# Other Notes

- **Future Improvements:**
  - Handling edge cases where the number of items exceeds the number of predefined colors by generating additional colors dynamically.

### CODE REVIEW

**Comment by TyHil** [comment]
Not positive on which way this should go but @TatvikReddy do you think we should move this logic to dashboard and pass the `colorMap` into the 2 components instead of duplicating the functionality?

**Comment by TatvikReddy** [comment]
@TyHil I don't know how this is organized, so I was hesitant to add separate components. However, it does make sense to have a separate component. If you want, I can do that.

**Comment by TyHil** [comment]
I just meant defining `colorMap` in dashboard then passing it as a prop to `compare` and `searchResultsTable`. No new component necessary, its just we have this code in 2 files and it could be good to just have it in `dashboard` and pass the result to the components that need it.

```
const colorMap: { [key: string]: string } = {};
compare.forEach((course, index) => {
  colorMap[searchQueryLabel(course)] =
    searchQueryColors[index % searchQueryColors.length];
});
```

**Comment by TatvikReddy** [comment]
Got it will do, sorry for the late reply

**Comment by TyHil** [comment]
no worries at all! thanks!

**Comment by TatvikReddy** [comment]
@TyHil I finished my changes, but to push those changes, I need to close this pull request. When I did that, it told me it was successfully deployed. 

How do I take back my pull request to update my changes?

**Comment by TyHil** [comment]
Any commits you push to the `251-feature-request-compare-colors-on-lhs` branch should just appear in the pull request, no need to make a new one or anything. If you made your changes on another branch you can open a pull request for that branch and close this one.

**Comment by TatvikReddy** [comment]
I mean, I am unable to push changes to this branch because github desktop can't push changes to this branch anymore, and I want to redo this pull request over because as I have different changes now

**Comment by TyHil** [comment]
I have no idea why that's happening. Maybe make a new branch off this branch? Or make a new branch off develop and cherry pick your commits over? Or try git in the terminal?

**Comment by TatvikReddy** [comment]
@TyHil, check now if everything is all right.

**Review by TyHil — APPROVED** [review]
Looks great!

**Comment by TyHil** [comment]
@AbhiramTadepalli can you give a final check over before merging!

**Review by AbhiramTadepalli — APPROVED** [review]
Alright, looks great!

**Pull request merged**
