### PR TITLE
Updated RMP Tags

### PR DESCRIPTION
**Pull request by GovindRangappa**
## Overview

Resolves RMP Tags being loaded in

Loaded in the RMP Tag data and output the top 10 under the graph

## What Changed

singleProfInfo.tsx was the only updated file. Added a section for the tag data to be loaded in

### CODE REVIEW

**Comment by AbhiramTadepalli** [comment]
@GovindRangappa @RVC13850 @TyHil is there any reason to ever omit tags from the top 10 because of their frequency?

https://utd-trends-1qa6ktyhi-utdnebula.vercel.app/dashboard?searchTerms=Gopal+Gupta
Like `Tough grader, (1) Skip class? You won't pass. (1), Amazing lectures (1), Clear grading criteria (1)`

I'm leaning towards leaving it as is because you can see the frequency

**Comment by AbhiramTadepalli** [comment]
Also (all 3 of you) for the above commit:
- I removed outline
- I made the text bigger. Should it go back to being smaller? Should I add padding? Is it fine as-is?
- In dark mode, should the bg color be darker?

What are your thoughts on these changes?

**Comment by AbhiramTadepalli** [comment]
image
vs
image

---

Should the overall tooltip have a hover at all?

**Comment by TyHil** [comment]
> @TyHil is there a better way to find topTags in `searchResultsTable.tsx`?

Looks good to me. We could do the sorting immediately once the data is fetched tho so it's not done in multiple places

@GovindRangappa what do you think about the other questions?

**Comment by RVC13850** [comment]
on light mode make it cornflower 100. on dark mode maybe keep the outline and match color with star

**Comment by AbhiramTadepalli** [comment]
@GovindRangappa @TyHil do you think (in dark mode) the color of the tag **needs** to be the same as the stars?

**Comment by TyHil** [comment]
Depends on how much we want to emphasize the tags. I'm not sure if they really need to pop like that

**Comment by GovindRangappa** [comment]
I like how the purple make the tags in the dropdown card look in dark mode. Only thing that I think has the potential to look better is centering the tags above the course name when hovered over rather than staggering them to the right. I do like the commas better than the | thing as it's a familiar punctuation that people are used to seeing and understanding.

**Comment by AbhiramTadepalli** [comment]
WHAT! ANIMATIONS!!!!!!!

**Comment by AbhiramTadepalli** [comment]
guys this might increase the engagement time on our website I WILL BE CLICKING THE MORE TAGS ANIMATION

**Comment by AbhiramTadepalli** [comment]
Andrew Nemec has no ratings - https://utd-trends-l3ddjbdvm-utdnebula.vercel.app/dashboard?searchTerms=Andrew+Nemec -> Should indicate no tags found?
B. Chitturi's RMP is not found by trends - https://utd-trends-l3ddjbdvm-utdnebula.vercel.app/dashboard?searchTerms=Bhadrachalam+Chitturi -> No tag on hover, maybe it should indicate that there are no tags found?

**Comment by TyHil** [comment]
> Andrew Nemec has no ratings - https://utd-trends-l3ddjbdvm-utdnebula.vercel.app/dashboard?searchTerms=Andrew+Nemec -> Should indicate no tags found? B. Chitturi's RMP is not found by trends - https://utd-trends-l3ddjbdvm-utdnebula.vercel.app/dashboard?searchTerms=Bhadrachalam+Chitturi -> No tag on hover, maybe it should indicate that there are no tags found?

oh yeah good point, lemme fix that

**Comment by AbhiramTadepalli** [comment]
The B. Chitturi case messes with the overall no-tag

**Comment by AbhiramTadepalli** [comment]
@TyHil idt that fixes Chitturi. I get nothing on hover for him. I think it's because his rmp data is null (same for overall)

**Comment by TyHil** [comment]
@AbhiramTadepalli ok that should do it. It will either say "No Tags Available" or list the tags on every results unless it's just a course, like "CS 1200 (Overall)"

**Review by AbhiramTadepalli — APPROVED** [review]
Yep, Looks good!

**Pull request merged**
