### PR TITLE
Feature/rmp link

### LINKED ISSUE #70: [Feature Request] Professor card RMP link
# Overview
The `ProfessorCard.tsx` component should link to the relevant Rate My Professors page from which the data was pulled so users can access the extra information available there. This could would as the top left text in the card, the professor's name, becoming that link.

# Proposal
A new prop with the Rate My Professors link the data was found on would need to be passed to the `ProfessorCard.tsx` component. The professor's name would then need to be displayed as a next.js Link component with the relevant link.

### PR DESCRIPTION
**Pull request by George-Zhang5246**
## Overview

Resolves #70
Changes the professor name to also be a link to the rmp search of their page 

## What Changed

added a link to CardContents.tsx

## Other Notes

To-do:
Format the professor name as a link
Determine whether to open link in new tab or current tab
Try to link to their direct page, instead of their search

### CODE REVIEW

**Comment by TyHil** [comment]
I think the link rendering as blue with an underline and opening in a new tab are essential features to add before this gets merged.

**Comment by iamwood** [comment]
> I think the link rendering as blue with an underline and opening in a new tab are essential features to add before this gets merged.

This is definitely the case. There is nothing to indicate that the name is a link.

**Comment by Jake3231** [comment]
@George-Zhang5246 With the latest changes, can you please rebase this branch to `develop` ahead of review?

**Comment by TyHil** [comment]
@Jake3231, I undid the changes I made that @George-Zhang5246 is addressing in PR #111 and went ahead and merged into develop.

**Comment by Jake3231** [comment]
I'm probably missing something very obvious, though where are `CardContents` and `ProfessorCard` being used currently?

**Comment by TyHil** [comment]
Thanks for catching that. `CardContents` was redundant and replaced with `ProfessorCard`. I must have forgotten to delete it when merging. There also shouldn't have needed to be any changes to `autocomplete_graph.json`.

**Review by Jake3231 — APPROVED** [review]

**Review by iamwood — APPROVED** [review]
Looks good to merge

**Pull request merged**
