### PR TITLE
chore: added semester dropbox & dropdown menu

### PR DESCRIPTION
**Pull request by sparklingwter**
completed:
* semester dropbox
* dropdown menu with all the academic year options
* select all
* selecting individual works
* select all is chosen at default

will not be completed in this PR:
* recent option does not work

### CODE REVIEW

**Comment by TyHil** [comment]
decided to just remove the grade data chip instead of the whole result when filtering to the point of no GPA for a result

**Comment by AbhiramTadepalli** [comment]
> decided to just remove the grade data chip instead of the whole result when filtering to the point of no GPA for a result

I think the result should be removed

**Comment by AbhiramTadepalli** [comment]
Maaybe for deselect all, I like your idea, but if I select 1 semester, every result w/o gpa should disappear

**Comment by AbhiramTadepalli** [comment]
How does this impact compare page?

Whatever the filter is set to impacts ALL the courses in compare.
- [ ] Need to handle blank data in compare (for GPA)

**Review by AbhiramTadepalli — APPROVED** [review]
Still some more to do later in #249

**Pull request merged**
