### PR TITLE
Standardize favicon and open graph data across Nebula

### PR DESCRIPTION
**Pull request by TyHil**
I was updating the Trends icons and decided to standardize the favicons and open graph data on all the Nebula sites. This PR updates the favicons to the new Nebula logo and adds/standardizes the [Open Graph](https://ogp.me/) metadata.

Every site should now follow the same template for the head tags in `_app.tsx` and `_document.tsx` which all link to the same corresponding icons. I also stored this icons in [this drive link](https://drive.google.com/drive/folders/1zHHQVsNNeHIr48K0DzpI6KZpIDqYFLgz?usp=sharing).

Other sites PRs:
https://github.com/UTDNebula/utd-trends/pull/123
https://github.com/UTDNebula/website-v2/pull/19
https://github.com/UTDNebula/jupiter/pull/175
https://github.com/UTDNebula/planner/pull/731

### CODE REVIEW

**Comment by Jake3231** [comment]
For some reason It looks like the favicon aren't showing, is that just me/my browser being weird?

**Comment by Jake3231** [comment]
> For some reason It looks like the favicon aren't showing, is that just me/my browser being weird?

From today's discussion: SVG favicons aren't supported on many browsers, including Safari.

**Comment by Jake3231** [comment]
Screenshot 2023-11-02 at 1 20 24 PM
@TyHil This is what I see now on Safari.

**Comment by TyHil** [comment]
That looks good. Chrome is falling back to the ico file too though so I want to fix that then it should be ready.

**Comment by TyHil** [comment]
Ok @Jake3231 I'm confirming with design whether the icon color should be black or #090b2c before this PR is ready. But svg ico fallback issue should be resolved.

**Comment by Jake3231** [comment]
Looks great overall! Just as a minor thing, from a design perspective - should the Nebula "N" have a bolder appearance? it looks thin relative to the text.

Screenshot 2023-11-09 at 10 39 54 AM

**Comment by TyHil** [comment]
I bumped the icon size, good idea

**Comment by Jake3231** [comment]
The image size looks good! The only thing now is that it looks like the layout of the nav bar is different somehow

Screenshot 2023-11-09 at 1 01 11 PM

**Comment by Jake3231** [comment]
Screenshot 2023-11-09 at 1 02 51 PM
Looks like the image width is too large

**Comment by TyHil** [comment]
Ah, Safari. Thanks for noticing. How does it look now?

**Comment by Jake3231** [comment]
Looks good!

I didn't expect Safari to cause this many issues!

**Review by Jake3231 — APPROVED** [review]
Looks good! Just as one last thing, are all of the new image assets used even with the latest fixes?

**Comment by TyHil** [comment]
Yes, I believe so

**Pull request merged**
