### PR TITLE
Update ratemyprofessorScraper.ts

### PR DESCRIPTION
**Pull request by George-Zhang5246**
Fix the format of the scraper

## What Changed

ratemyprofessorScraper url format changed

### CODE REVIEW

**Review by TyHil — CHANGES_REQUESTED** [review]
Just run prettier (`npx prettier --write .`) and it'll be good!

**Comment by Jake3231** [comment]
@TyHil Per the discussion in #88 , can this be closed?

**Comment by TyHil** [comment]
@Jake3231 no this PR fixes RMP scraping. #88 just adds a link to access RMP directly from Trends.

**Comment by Jake3231** [comment]
I see, I misunderstood what you said, now I got it.

**Review by Jake3231 — COMMENTED** [review]
Looks good! Ready to go pending the changes mentioned by @TyHil

**Review by TyHil — APPROVED** [review]

**Review by iamwood — APPROVED** [review]
Looks good to merge.

**Pull request merged**
