### PR TITLE
#199 resizable dashboard

### PR DESCRIPTION
**Pull request by HershLalwani**
## Overview

Completes #199 

A way for the user to resize the RHS and LHS to improve readability of the compare tab and search list.

## What Changed

Changes in dashboard/index.tsx swapped grid for react-resizable-panels to display the RHS & LHS. There are functions to show the correct UI when accessing from desktop or mobile.

## Other Notes

Several Libraries were attempted, but react-resizable-panels worked best for our needs.

### CODE REVIEW

**Comment by TyHil** [comment]
@AbhiramTadepalli double check LHS getting too small and mobile issues
maybe also snapping back to 50/50?

**Comment by TyHil** [comment]
Mobile seems to work on firefox for me but not chrome, may just need to go back to the old Grid based on a useMediaQuery

**Comment by TyHil** [comment]
@AbhiramTadepalli this should be ready now except I can't seem to get the sticky RHS working when merging in develop

**Comment by TyHil** [comment]
@AbhiramTadepalli Ok figured it out. Apparently overflow hidden on any parents screws with position sticky. All ready now.

**Comment by AbhiramTadepalli** [comment]
Okay so every time you add to compare it makes the rhs's minimum width wider. imo minwidth should stay the same because we have horizontal scroll in compare

**Comment by TyHil** [comment]
Idk why setting min width fixes this but it does

**Comment by AbhiramTadepalli** [comment]
ah sorry. Bug:

1) Make LHS bigger, 
2) open a card, 
3) make LHS smaller, 
4) the LHS does not get smaller, RHS just moves on top of it. Expected behavior is LHS resizes (including the contents of the card)

**Comment by TyHil** [comment]
> @TyHil one last question The LHS locks at a min-width. In split-screen (when the browser window is half the size) the RHS keeps going until the edge of the name. Is that the intended behavior?
> 
> In full-screen, the RHS just stops at the LHS's min-width

i dont't quite get this, can you screenshot?



> ah sorry. Bug:
> 
>     1. Make LHS bigger,
> 
>     2. open a card,
> 
>     3. make LHS smaller,
> 
>     4. the LHS does not get smaller, RHS just moves on top of it. Expected behavior is LHS resizes (including the contents of the card)

im getting this behavior like 1 in 10 times, but if you re expand the LHS and re collapse it behaves as intended. is that acceptable?

**Comment by AbhiramTadepalli** [comment]
> > @TyHil one last question The LHS locks at a min-width. In split-screen (when the browser window is half the size) the RHS keeps going until the edge of the name. Is that the intended behavior?
> > In full-screen, the RHS just stops at the LHS's min-width
> 
> i dont't quite get this, can you screenshot?

image
It covers the bubbles, does not make the row skinnier

**Comment by AbhiramTadepalli** [comment]
> im getting this behavior like 1 in 10 times, but if you re expand the LHS and re collapse it behaves as intended. is that acceptable?

Do you know why it's inconsistent? Or the cause?

**Comment by TyHil** [comment]
I have no idea

**Comment by AbhiramTadepalli** [comment]
Since it mostly works, I'll merge it in
- [ ] [Bug]: Resizable dashboard does not shrink an expanded card on the LHS, sometimes

**Review by AbhiramTadepalli — APPROVED** [review]
Great work @HershLalwani

**Pull request merged**
