### PR TITLE
Remove Vercel Analytics

### PR DESCRIPTION
**Pull request by TyHil**
Not positive we want to do this but since we now have Google Analytics, we can remove Vercel analytics

### CODE REVIEW

**Comment by AbhiramTadepalli** [comment]
I want to keep both for a bit and compare which one is better

**Comment by TyHil** [comment]
Just lost Vercel analytics for the next 7 days since its the free tier

**Comment by AbhiramTadepalli** [comment]
Google analytics does pretty much everything except speed insights
Which we don't have to monitor imo it's pretty high

**Comment by TyHil** [comment]
Speed insights is a separate thing in Vercel. This PR keeps speed insights while removing analytics

**Review by AbhiramTadepalli — APPROVED** [review]
Bye bye

**Pull request merged**
