### PR TITLE
Feature/related classes list

### LINKED ISSUE #49: [Feature Request] Related Classes List
# Overview

We want our application to suggest related classes based on those already being searched. These suggestions will be presented in a list on the left-hand side of the dashboard page. The contents should update whenever the selections change. This could likely be completed via an extension of the Autocomplete API.

# Proposal

A new component needs to be developed that follows the design outlined in the Figma. It should consist most basically of a list whose contents update as the selected courses are changed. It would likely be good to look into the `SearchTermCard` component that already exists as a jumping-off point or potential reusable component.

## Supplementary Information
 
dashboard-relatedclassescircled

Here is the design from our Figma, with the specific component circled in a red box (don’t include the red box in your implementation).

### PR DESCRIPTION
**Pull request by TyHil**
## Overview

Resolves #49 

Implements a related classes side bar. I called it "Related Queries" since not everything that can be searched is a class, professors for example, but this could be changed. Related classes are generated using the autocomplete API and primarily suggest different professors for courses if possible, and the next level of data (prof --> prof + course) if not.

## What Changed

Added a new way to call the autocomplete API with a SearchQuery.
Added new RelatedClasses component and RelatedTermCard.
Added a ToolTip to the related classes add query button and went ahead and added that to other buttons too.

### CODE REVIEW

**Comment by TyHil** [comment]
Integrated Common Types and Functions (PR #103) into branch.

**Comment by Jake3231** [comment]
Is it expected that sometimes the "related queries" section doesn't appear when selecting a course? This seems like an error, as the UI layout adjusts, without the view appearing.

https://github.com/UTDNebula/utd-trends/assets/13911970/959e121f-0d41-420c-9e31-2070dfb70369

**Comment by TyHil** [comment]
Ah, there were layout issues. I switched to using MUI Grid, should be working well now.

**Review by iamwood — APPROVED** [review]
Looks good to merge.

**Pull request merged**
