### PR TITLE
Feature/hide data icon button

### PR DESCRIPTION
**Pull request by TyHil**
## Overview

Allow hiding queries from all graphs and professor tab

## What Changed

Added a button in each `searchTermCard` to toggle visibility. This generates a visibility array in the `expandableSearchGrid` which is then passed to the dashboard. The dashboard does not rerun data fetching and instead excludes datasets at the last time possible, before becoming props for the graphs/prof cards.

### CODE REVIEW

**Comment by Jake3231** [comment]
Overall looks good, and seems very useful! From a design perspective, is the visibility toggle discoverable?

**Comment by TyHil** [comment]
I just tabbed through and it could access the toggles

**Comment by Jake3231** [comment]
The biggest thing I noticed is that it seems to only appear when you hover over the color of a selected course, and there's no indication that the toggle is hidden there.

**Comment by TyHil** [comment]
Good point. I remember thinking it looked weird to always have the Visibility icon there but its better to be clear. New commit should fix that

**Review by Jake3231 — APPROVED** [review]
Overall looks good! cc @iamwood as well on design

**Review by iamwood — APPROVED** [review]
Looks good to merge

**Pull request merged**
