### PR TITLE
Blank search updates

### PR DESCRIPTION
**Pull request by TyHil**
## Overview

Removed suggestions on the homepage before typing anything.
Set suggestions on homepage to be based on last inputted query. So if you add "CS 1200" to the expandable search grid and click on the search bar, the immediate suggestions that pop up will be things like "CS 1200 John Cole", "CS 1200 Prof name", and so on. This is like a primitive related classes box.

## What Changed

Made other bug fixes along the way and improvements based on the MUI documentation but primary changes in are in the search bar files.

### CODE REVIEW

**Comment by TyHil** [comment]
Integrated Common Types and Functions (PR #103) into branch.

**Comment by Jake3231** [comment]
The new behavior seems improved! @TyHil Just to verify, is all new behavior working as expected with the latest changed to develop?

**Comment by TyHil** [comment]
@Jake3231 Yup, all working

**Comment by Jake3231** [comment]
@TyHil Is it correct that this has no conflicts with the changes in #97 ?

**Review by Jake3231 — APPROVED** [review]

**Comment by TyHil** [comment]
@Jake3231 I don't know. They both work independently and I don't see any reason they shouldn't work together. Can we merge one into dev so I can run some tests and see?

**Comment by Jake3231** [comment]
Sounds good, it looked like that to me as well. Once one is merged we can verify.

**Review by iamwood — APPROVED** [review]
Looks good to merge

**Pull request merged**
