### PR TITLE
Feature dashboard results sorting 

### LINKED ISSUE #184: [Feature Request]: Default dashboard results sorting
# Overview

Currently the default sorting is random. This is unintuitive.

# Proposal

A default sorting can be set up in the `generateCombosTable.ts`. This script maps searches to a list of unsorted search results. The last step in the script can be to sort all the results alphabetically.

### PR DESCRIPTION
**Pull request by sparklingwter**
## What Changed

resolves #184 
added a sorting function in generateCombos, sorted by prefix, course number, last name and first name of professors.

### CODE REVIEW

**Comment by AbhiramTadepalli** [comment]
I copy-pasted @sparklingwter's logic for sorting by name into the searchResultsTable so that users can also sort by name after they get the initially default-sorted list.

**Comment by AbhiramTadepalli** [comment]
Question for @sparklingwter @TyHil - should the (Overall) result stay at the top for both sorting asc by name and sorting desc by name?

**Comment by TyHil** [comment]
I think the (Overall) result should stay at the top for both sorting asc by name and sorting desc by name.

I don't think this code quite works tho. It always sorts by prof since we're looking at course prof combos `'profLast' in a && 'profLast' in b` is always true. So when you look up a prof, it can't sort by course.

I think you'd want to sort by whichever searchTerm there are fewer of? like if there are fewer courses in the search results, sort by courses, maybe

Also seems like the arrow direction might be swapped

**Comment by sparklingwter** [comment]
hi, why am i still writing a sorting function when searchResultTable is gonna overwrite my codes?

**Comment by TyHil** [comment]
i think the sorting in searchResultTable is necessary when searching for multiple courses or multiple profs to merge the 2 results.

your sorting in the combos table i think probably speeds up this process by allowing it to start with 2 already sorted lists.

**Comment by sparklingwter** [comment]
So should I sort my results only in generatecombos or should I also modify searchResultTable? Since I doubt I can see my changes in generatecombos..?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by TyHil** [comment]
what you did in generatecombos looks great. I think Abhiram is going to finish up a couple things in searchResultTable, then the PR will be ready to merge

**Review by AbhiramTadepalli — APPROVED** [review]
Great job Annie!

**Comment by AbhiramTadepalli** [comment]
phew

**Comment by AbhiramTadepalli** [comment]
Merged in https://github.com/UTDNebula/utd-trends/pull/229 sorry for the delay

**Pull request closed without merging**
