### PR TITLE
Fixed sorting bug

### PR DESCRIPTION
**Pull request by RVC13850**
## Overview
Fixed issue #170 where it would crash when sorted more than 2 times.

## What Changed
Added a check to make sure aGrades and bGrades objects were defined.

### CODE REVIEW

**Comment by TyHil** [comment]
This seems to have removed the check if they're both undefined/not loaded. It was this:
```
if (aGrades.state !== 'done' && bGrades.state !== 'done') {
  return 0;
}
```
If there's not a reason, can you bring it back (for grades and rmp) and apply your changes from the other if statements to these as well.

**Comment by RVC13850** [comment]
There was no particular reason. I added it back and its working so no issues

**Comment by TyHil** [comment]
Looks excellent then! I'll let @AbhiramTadepalli review

**Review by AbhiramTadepalli — APPROVED** [review]
Looks great!

**Pull request merged**
