### PR TITLE
Added Link HTML Element

### LINKED ISSUE #35: [Feature Request] Add link to top menu bar component
# Overview
It is an expected feature to be able to click the branding of a menu bar to navigate back to the home screen. Add this functionality to this component.

# Proposal
Surround the branding divs with a Link tag

### PR DESCRIPTION
**Pull request by TyHil**
Added a link HTML element in the topMenu.tsx component

## Overview

List the GitHub issues containing the issues relevant to this pull request.

Resolves #35

Clicking on the website name in the header now links to the homepage.

## What Changed

Added a `<a href="/">` element in topMenu.tsx

### CODE REVIEW

**Comment by shoaibhuq** [comment]
We want to use NextJS to link the pages together. It allows us to have more control over navigation behavior.
Check out this link: [https://nextjs.org/learn/basics/navigate-between-pages/link-component](url)

**Comment by TyHil** [comment]
I believe that's what my second commit did with the `<Link href="/">` line right?

**Comment by shoaibhuq** [comment]
> I believe that's what my second commit did with the `<Link href="/">` line right?

Yes, I see that now, apologies, you did it correctly!

**Review by shoaibhuq — APPROVED** [review]
Functioning properly looks good!

**Pull request merged**
