### PR TITLE
bg of filter changes when filter is selected

### PR DESCRIPTION
**Pull request by justjaiom**
## Overview

List the GitHub issues containing the issues relevant to this pull request.

fixed the proposal: "When a filter has been selected, make the filter box have a darker shade / color"

## What Changed

I changed filters.txt, specifically the class names in the form control. I edited al three form controls so that a darker grey is presented when a filter is applied. 

## Other Notes

I used a dark grey (grey-900) for the dark theme, but if it doesn't fit into the color theme or the design, let me know so i can change it.

### CODE REVIEW

**Comment by AbhiramTadepalli** [comment]
This doesn't work well in dark mode fyi

**Comment by justjaiom** [comment]
> This doesn't work well in dark mode fyi



> This doesn't work well in dark mode fyi

**Comment by AbhiramTadepalli** [comment]
1) should "All Semesters" be highlighted as selected? It does bring attention to the semester filter, but it also is the default state
2) What do we think about the tooltip for semester

**Comment by TyHil** [comment]
1. I think current behavior is good: highlight when not at default. but nitpick it should also be highlighted when none are selected
2. tbh i don't see the point. i think the tooltips should describe that its a filter and what you're filtering on like "Filter by minimum letter grade across course sections"
3. i think that's probably an inevitable accessibility thing

**Comment by AbhiramTadepalli** [comment]
> 1. I think current behavior is good: highlight when not at default. but nitpick it should also be highlighted when none are selected

**Comment by AbhiramTadepalli** [comment]
> 2\. tbh i don't see the point. i think the tooltips should describe that its a filter and what you're filtering on like "Filter by minimum letter grade across course sections"

rn it's dynamic so if something is selected the tag changes

**Comment by TyHil** [comment]
> rn it's dynamic so if something is selected the tag changes

oh ok i see. but i can already see that information in the dropdown without hovering

**Review by AbhiramTadepalli — APPROVED** [review]
Great!

**Review by TyHil — APPROVED** [review]
all good!

**Pull request merged**
