### PR TITLE
288 bug handle null rmp data

### LINKED ISSUE #288: [Bug]: LHS & RHS handle null RMP data
### What did you expect to happen?

If there is no RMP data, it should be indicated properly (https://trends.utdnebula.com/dashboard?searchTerms=Yu+Chung+Ng)

### What happened?

I get 0 as the rating (when it should be null) and -1% for would take again.
image

Same applies for the rating component, hovers on LHS, and RHS compare
image

### Version

trends.utdnebula.com

### What browsers are you seeing the problem on?

_No response_

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by George-Zhang5246**
## Overview

Resolves #288 

## What Changed

ratemyprofessorScraper now gives an error when the rmp data contains 0 ratings.

### CODE REVIEW

**Comment by AbhiramTadepalli** [comment]
@TyHil in relation to our other convo about no grade data, should we show some message that this prof has no RMP data?

**Comment by TyHil** [comment]
Hmm yeah I suppose it should maybe just say reviews: 0 and have the link to the RMP page

**Comment by George-Zhang5246** [comment]
I guess I can do that, though it would need modifications to all of the components as opposed to just the RMP scraper.

**Review by AbhiramTadepalli — APPROVED** [review]
Great job @George-Zhang5246!

**Review by TyHil — APPROVED** [review]

**Pull request merged**
